# Generated by Django 5.2.12 on 2026-03-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_categoria_lancamento_categoria'),
        ('servicos', '0013_veiculo_ordemservico_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.veiculo'),
        ),
    ]
