# Generated by Django 5.2.12 on 2026-03-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_lancamento_veiculo'),
        ('servicos', '0014_veiculo_combustivel_veiculo_consumo_km_litro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='servicos.ordemservico'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(),
        ),
    ]
