# Generated by Django 5.2.12 on 2026-03-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lancamento_ordem_servico_alter_lancamento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
