# Generated by Django 5.2.12 on 2026-03-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_remove_servico_cliente_delete_cliente_delete_servico'),
        ('servicos', '0014_veiculo_combustivel_veiculo_consumo_km_litro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='servicos.servico'),
        ),
    ]
