# Generated by Django 5.2.12 on 2026-03-06 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='data_servico',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='servico',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicos.tiposervico'),
            preserve_default=False,
        ),
    ]
