# Generated by Django 5.2.12 on 2026-03-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_tiposervico_rename_data_servico_servico_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
    ]
