# Generated by Django 5.2.12 on 2026-03-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_ordemservico_itemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
