# Generated by Django 5.2.12 on 2026-03-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_ordemservico_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='numero_funcionarios',
            field=models.IntegerField(default=1, verbose_name='Funcionários'),
        ),
    ]
