# Generated by Django 5.2.12 on 2026-03-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_alter_ordemservico_numero_funcionarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_funcionarios',
            field=models.IntegerField(default=1, verbose_name='Funcionários'),
        ),
    ]
