# Generated by Django 5.2.12 on 2026-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_alter_ordemservico_numero_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='km_rodado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='KM rodado'),
        ),
    ]
