# Generated by Django 5.2.12 on 2026-03-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0010_ordemservico_km_rodado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
