# Generated by Django 5.2.12 on 2026-03-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, to='servicos.funcionario'),
        ),
    ]
