# Generated by Django 5.2.12 on 2026-03-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0013_veiculo_ordemservico_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gnv', 'GNV'), ('flex', 'Flex')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='consumo_km_litro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Consumo (km/l)'),
        ),
    ]
