# Generated by Django 5.2.12 on 2026-03-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0014_veiculo_combustivel_veiculo_consumo_km_litro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='preco_combustivel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Preço do combustível (R$/L)'),
        ),
    ]
